name: automotive_edp
version: '2.0.0'
config-version: 2
profile: automotive_edp
model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]
models:
  automotive_edp:
    staging:
      +schema: STAGING
      +materialized: view
    curated:
      +schema: CURATED
      +materialized: table
    marts:
      +schema: MARTS
      +materialized: table
