version: 2
sources:
  - name: raw
    database: "{{ env_var('SNOWFLAKE_DATABASE', 'ENTERPRISE_PLATFORM') }}"
    schema: RAW
    tables:
      - name: vehicle_events
      - name: customers
      - name: vehicles
      - name: sales_orders
      - name: campaign_events
      - name: support_tickets
      - name: financial_transactions
      - name: ota_deployments
