USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS ENTERPRISE_DATA;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.RAW;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.STAGING;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.CURATED;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.MARTS;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.GOVERNANCE;

CREATE WAREHOUSE IF NOT EXISTS EDP_INGEST_WH WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS EDP_TRANSFORM_WH WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS EDP_BI_WH WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

CREATE ROLE IF NOT EXISTS EDP_ENGINEER;
CREATE ROLE IF NOT EXISTS EDP_MARKETING;
CREATE ROLE IF NOT EXISTS EDP_SALES;
CREATE ROLE IF NOT EXISTS EDP_FINANCE;
CREATE ROLE IF NOT EXISTS EDP_SUPPORT;

GRANT USAGE ON DATABASE ENTERPRISE_DATA TO ROLE EDP_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ENTERPRISE_DATA TO ROLE EDP_ENGINEER;
GRANT USAGE ON WAREHOUSE EDP_INGEST_WH TO ROLE EDP_ENGINEER;
GRANT USAGE ON WAREHOUSE EDP_TRANSFORM_WH TO ROLE EDP_ENGINEER;
GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE ENTERPRISE_DATA TO ROLE EDP_ENGINEER;
