USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS ENTERPRISE_DATA COMMENT='Automotive enterprise data platform';
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.RAW;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.STAGING;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.CURATED;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.MARTS;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.GOVERNED;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DATA.GOVERNANCE;

CREATE WAREHOUSE IF NOT EXISTS EDP_INGEST_WH WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE WAREHOUSE IF NOT EXISTS EDP_BI_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;

CREATE ROLE IF NOT EXISTS EDP_ENGINEER;
CREATE ROLE IF NOT EXISTS EDP_MARKETING;
CREATE ROLE IF NOT EXISTS EDP_SALES;
CREATE ROLE IF NOT EXISTS EDP_SUPPORT;
CREATE ROLE IF NOT EXISTS EDP_FINANCE;
CREATE ROLE IF NOT EXISTS EDP_DELIVERY;
GRANT ROLE EDP_ENGINEER TO ROLE SYSADMIN;
SET BOOTSTRAP_USER = CURRENT_USER();
GRANT ROLE EDP_ENGINEER TO USER IDENTIFIER($BOOTSTRAP_USER);
GRANT USAGE ON WAREHOUSE EDP_INGEST_WH TO ROLE EDP_ENGINEER;
GRANT USAGE ON WAREHOUSE EDP_BI_WH TO ROLE EDP_ENGINEER;
GRANT USAGE ON DATABASE ENTERPRISE_DATA TO ROLE EDP_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE, CREATE STAGE, CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE ENTERPRISE_DATA TO ROLE EDP_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE, CREATE STAGE, CREATE FILE FORMAT ON FUTURE SCHEMAS IN DATABASE ENTERPRISE_DATA TO ROLE EDP_ENGINEER;
