USE DATABASE ENTERPRISE_DATA;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS EVENTS (
  EVENT_ID STRING,
  EVENT_TS TIMESTAMP_TZ,
  EVENT_TYPE STRING,
  CUSTOMER_ID NUMBER,
  SESSION_ID NUMBER,
  PRODUCT_ID NUMBER,
  CAMPAIGN_ID NUMBER,
  AMOUNT NUMBER(18,2),
  CHANNEL STRING,
  REGION STRING,
  INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  RECORD_METADATA VARIANT
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID NUMBER, FULL_NAME STRING, EMAIL STRING, PHONE STRING,
  CITY STRING, SEGMENT STRING, CREATED_AT TIMESTAMP_NTZ
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
  PRODUCT_ID NUMBER, CATEGORY STRING, BRAND STRING,
  LIST_PRICE NUMBER(18,2), COST_PRICE NUMBER(18,2)
);
CREATE TABLE IF NOT EXISTS CAMPAIGNS (
  CAMPAIGN_ID NUMBER, CHANNEL STRING, CAMPAIGN_NAME STRING,
  START_DATE DATE, DAILY_BUDGET NUMBER(18,2)
);
CREATE TABLE IF NOT EXISTS SUPPORT_TICKETS (
  TICKET_ID NUMBER, CUSTOMER_ID NUMBER, REASON STRING, PRIORITY STRING,
  OPENED_AT TIMESTAMP_NTZ, STATUS STRING,
  FIRST_RESPONSE_MINUTES NUMBER(18,2), RESOLUTION_MINUTES NUMBER(18,2)
);
