USE DATABASE ENTERPRISE_DATA;
USE SCHEMA RAW;
CREATE TABLE IF NOT EXISTS SOURCE_SEED (
  SOURCE_ROW_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_ID STRING,
  PRODUCT_ID STRING,
  AMOUNT NUMBER(18,2),
  EVENT_TS TIMESTAMP_NTZ,
  EMAIL STRING,
  CITY STRING,
  SOURCE_PAYLOAD VARIANT,
  INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
