USE DATABASE ENTERPRISE_DATA;
USE SCHEMA GOVERNANCE;

CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('EDP_ENGINEER','EDP_MARKETING','EDP_SUPPORT') THEN VAL
    WHEN VAL IS NULL THEN NULL
    ELSE REGEXP_REPLACE(VAL, '(^.).*(@.*$)', '\\1***\\2')
  END;

CREATE OR REPLACE MASKING POLICY MASK_PHONE AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('EDP_ENGINEER','EDP_SUPPORT') THEN VAL
    WHEN VAL IS NULL THEN NULL
    ELSE CONCAT('******', RIGHT(VAL,4))
  END;

ALTER TABLE ENTERPRISE_DATA.RAW.CUSTOMERS MODIFY COLUMN EMAIL
  SET MASKING POLICY ENTERPRISE_DATA.GOVERNANCE.MASK_EMAIL;
ALTER TABLE ENTERPRISE_DATA.RAW.CUSTOMERS MODIFY COLUMN PHONE
  SET MASKING POLICY ENTERPRISE_DATA.GOVERNANCE.MASK_PHONE;

CREATE TAG IF NOT EXISTS DATA_CLASSIFICATION ALLOWED_VALUES 'PUBLIC','INTERNAL','CONFIDENTIAL','PII';
ALTER TABLE ENTERPRISE_DATA.RAW.CUSTOMERS MODIFY COLUMN EMAIL SET TAG DATA_CLASSIFICATION='PII';
ALTER TABLE ENTERPRISE_DATA.RAW.CUSTOMERS MODIFY COLUMN PHONE SET TAG DATA_CLASSIFICATION='PII';
ALTER TABLE ENTERPRISE_DATA.RAW.CUSTOMERS MODIFY COLUMN FULL_NAME SET TAG DATA_CLASSIFICATION='PII';
