USE ROLE ACCOUNTADMIN;
USE DATABASE ENTERPRISE_DATA;
CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_EMAIL AS (V STRING) RETURNS STRING -> CASE WHEN CURRENT_ROLE() IN ('EDP_ENGINEER') THEN V ELSE REGEXP_REPLACE(V, '(^.).*(@.*$)', '\\1***\\2') END;
CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_PHONE AS (V STRING) RETURNS STRING -> CASE WHEN CURRENT_ROLE() IN ('EDP_ENGINEER') THEN V ELSE CONCAT('******', RIGHT(V, 4)) END;
ALTER TABLE IF EXISTS RAW.CUSTOMERS MODIFY COLUMN EMAIL SET MASKING POLICY GOVERNANCE.MASK_EMAIL;
ALTER TABLE IF EXISTS RAW.CUSTOMERS MODIFY COLUMN PHONE SET MASKING POLICY GOVERNANCE.MASK_PHONE;
