USE DATABASE ENTERPRISE_DATA;

CREATE OR REPLACE DYNAMIC TABLE STAGING.STG_EVENTS
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = EDP_TRANSFORM_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
  EVENT_ID, EVENT_TS, UPPER(TRIM(EVENT_TYPE)) EVENT_TYPE,
  CUSTOMER_ID, SESSION_ID, PRODUCT_ID, CAMPAIGN_ID,
  COALESCE(AMOUNT,0) AMOUNT, UPPER(CHANNEL) CHANNEL, UPPER(REGION) REGION,
  INGESTED_AT
FROM RAW.EVENTS
WHERE EVENT_ID IS NOT NULL AND EVENT_TS IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE CURATED.FCT_COMMERCE_EVENTS
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = EDP_TRANSFORM_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
 e.*,
 c.SEGMENT CUSTOMER_SEGMENT,
 c.CITY,
 p.CATEGORY,
 p.BRAND,
 p.COST_PRICE,
 ca.CHANNEL CAMPAIGN_CHANNEL,
 ca.CAMPAIGN_NAME
FROM STAGING.STG_EVENTS e
LEFT JOIN RAW.CUSTOMERS c USING (CUSTOMER_ID)
LEFT JOIN RAW.PRODUCTS p USING (PRODUCT_ID)
LEFT JOIN RAW.CAMPAIGNS ca USING (CAMPAIGN_ID);
