USE ROLE PLATFORM_ROLE;
USE DATABASE ENTERPRISE_PLATFORM;

CREATE OR REPLACE SECURE VIEW GOVERNED.V_MARKETING_DASHBOARD AS
SELECT * FROM MARTS.MART_MARKETING_DAILY;

CREATE OR REPLACE SECURE VIEW GOVERNED.V_SALES_DASHBOARD AS
SELECT * FROM MARTS.MART_SALES_DAILY;

CREATE OR REPLACE SECURE VIEW GOVERNED.V_SUPPORT_DASHBOARD AS
SELECT * FROM MARTS.MART_SUPPORT_DAILY;

CREATE OR REPLACE SECURE VIEW GOVERNED.V_FINANCE_DASHBOARD AS
SELECT * FROM MARTS.MART_FINANCE_DAILY;

CREATE OR REPLACE SECURE VIEW GOVERNED.V_DELIVERY_DASHBOARD AS
SELECT * FROM MARTS.MART_DELIVERY_DAILY;

-- PLATFORM_ROLE owns these project views in the provisioned environment.
-- Department-specific Snowflake roles can be granted later by an account admin
-- if the account's governance model requires separate database roles.
