USE ROLE EDP_ENGINEER;
USE DATABASE ENTERPRISE_DATA;
CREATE OR REPLACE VIEW GOVERNANCE.V_PIPELINE_HEALTH AS
SELECT CURRENT_TIMESTAMP() AS OBSERVED_AT,
       (SELECT COUNT(*) FROM RAW.VEHICLE_EVENTS WHERE INGESTED_AT >= DATEADD('minute',-5,CURRENT_TIMESTAMP())) AS VEHICLE_EVENTS_5M,
       (SELECT MAX(INGESTED_AT) FROM RAW.VEHICLE_EVENTS) AS LAST_VEHICLE_EVENT,
       DATEDIFF('second',(SELECT MAX(INGESTED_AT) FROM RAW.VEHICLE_EVENTS),CURRENT_TIMESTAMP()) AS FRESHNESS_SECONDS;
