USE DATABASE ENTERPRISE_DATA;

CREATE OR REPLACE DYNAMIC TABLE MARTS.MART_MARKETING_DAILY
  TARGET_LAG = '1 minute'
  WAREHOUSE = EDP_TRANSFORM_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
  DATE_TRUNC('DAY',EVENT_TS) DAY,
  CAMPAIGN_ID, CAMPAIGN_CHANNEL, CAMPAIGN_NAME,
  COUNT_IF(EVENT_TYPE='PAGE_VIEW') IMPRESSIONS,
  COUNT_IF(EVENT_TYPE='SEARCH') SEARCHES,
  COUNT_IF(EVENT_TYPE='ADD_TO_CART') ADDS_TO_CART,
  COUNT_IF(EVENT_TYPE='ORDER_CREATED') CONVERSIONS,
  SUM(IFF(EVENT_TYPE='ORDER_CREATED',AMOUNT,0)) ATTRIBUTED_REVENUE
FROM CURATED.FCT_COMMERCE_EVENTS
GROUP BY ALL;

CREATE OR REPLACE DYNAMIC TABLE MARTS.MART_SALES_DAILY
  TARGET_LAG = '1 minute'
  WAREHOUSE = EDP_TRANSFORM_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
  DATE_TRUNC('DAY',EVENT_TS) DAY, REGION, CATEGORY, BRAND,
  COUNT_IF(EVENT_TYPE='ORDER_CREATED') ORDERS,
  SUM(IFF(EVENT_TYPE='ORDER_CREATED',AMOUNT,0)) GROSS_REVENUE,
  COUNT_IF(EVENT_TYPE='PAYMENT_AUTHORIZED') PAYMENT_AUTHS
FROM CURATED.FCT_COMMERCE_EVENTS
GROUP BY ALL;

CREATE OR REPLACE DYNAMIC TABLE MARTS.MART_FINANCE_DAILY
  TARGET_LAG = '1 minute'
  WAREHOUSE = EDP_TRANSFORM_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
  DATE_TRUNC('DAY',EVENT_TS) DAY,
  SUM(IFF(EVENT_TYPE='ORDER_CREATED',AMOUNT,0)) GROSS_REVENUE,
  SUM(IFF(EVENT_TYPE='ORDER_CREATED',COALESCE(COST_PRICE,0),0)) ESTIMATED_COGS,
  SUM(IFF(EVENT_TYPE='ORDER_CREATED',AMOUNT*0.025,0)) ESTIMATED_PAYMENT_FEES,
  GROSS_REVENUE-ESTIMATED_COGS-ESTIMATED_PAYMENT_FEES NET_CONTRIBUTION
FROM CURATED.FCT_COMMERCE_EVENTS
GROUP BY ALL;

CREATE OR REPLACE DYNAMIC TABLE MARTS.MART_SUPPORT_DAILY
  TARGET_LAG = '5 minutes'
  WAREHOUSE = EDP_TRANSFORM_WH
  REFRESH_MODE = INCREMENTAL
AS
SELECT
  DATE_TRUNC('DAY',OPENED_AT) DAY, REASON, PRIORITY,
  COUNT(*) TICKETS,
  AVG(FIRST_RESPONSE_MINUTES) AVG_FIRST_RESPONSE_MINUTES,
  APPROX_PERCENTILE(RESOLUTION_MINUTES,0.95) P95_RESOLUTION_MINUTES,
  COUNT_IF(STATUS='RESOLVED')/NULLIF(COUNT(*),0)::FLOAT RESOLUTION_RATE
FROM RAW.SUPPORT_TICKETS
GROUP BY ALL;
