USE DATABASE ENTERPRISE_DATA;
USE SCHEMA MARTS;

CREATE OR REPLACE SECURE VIEW VW_MARKETING AS SELECT * FROM MART_MARKETING_DAILY;
CREATE OR REPLACE SECURE VIEW VW_SALES AS SELECT * FROM MART_SALES_DAILY;
CREATE OR REPLACE SECURE VIEW VW_FINANCE AS SELECT * FROM MART_FINANCE_DAILY;
CREATE OR REPLACE SECURE VIEW VW_SUPPORT AS SELECT * FROM MART_SUPPORT_DAILY;

GRANT USAGE ON DATABASE ENTERPRISE_DATA TO ROLE EDP_MARKETING;
GRANT USAGE ON SCHEMA ENTERPRISE_DATA.MARTS TO ROLE EDP_MARKETING;
GRANT USAGE ON WAREHOUSE EDP_BI_WH TO ROLE EDP_MARKETING;
GRANT SELECT ON VIEW ENTERPRISE_DATA.MARTS.VW_MARKETING TO ROLE EDP_MARKETING;

GRANT USAGE ON DATABASE ENTERPRISE_DATA TO ROLE EDP_SALES;
GRANT USAGE ON SCHEMA ENTERPRISE_DATA.MARTS TO ROLE EDP_SALES;
GRANT USAGE ON WAREHOUSE EDP_BI_WH TO ROLE EDP_SALES;
GRANT SELECT ON VIEW ENTERPRISE_DATA.MARTS.VW_SALES TO ROLE EDP_SALES;

GRANT USAGE ON DATABASE ENTERPRISE_DATA TO ROLE EDP_FINANCE;
GRANT USAGE ON SCHEMA ENTERPRISE_DATA.MARTS TO ROLE EDP_FINANCE;
GRANT USAGE ON WAREHOUSE EDP_BI_WH TO ROLE EDP_FINANCE;
GRANT SELECT ON VIEW ENTERPRISE_DATA.MARTS.VW_FINANCE TO ROLE EDP_FINANCE;

GRANT USAGE ON DATABASE ENTERPRISE_DATA TO ROLE EDP_SUPPORT;
GRANT USAGE ON SCHEMA ENTERPRISE_DATA.MARTS TO ROLE EDP_SUPPORT;
GRANT USAGE ON WAREHOUSE EDP_BI_WH TO ROLE EDP_SUPPORT;
GRANT SELECT ON VIEW ENTERPRISE_DATA.MARTS.VW_SUPPORT TO ROLE EDP_SUPPORT;
