-- Operational checks for freshness and query health.
SELECT * FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLES(RESULT_LIMIT => 100));

SELECT
  QUERY_ID, USER_NAME, ROLE_NAME, WAREHOUSE_NAME,
  TOTAL_ELAPSED_TIME/1000 ELAPSED_SECONDS, BYTES_SCANNED, ROWS_PRODUCED,
  QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('hour',-1,CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC
LIMIT 100;
